### ISSUE TITLE
External interrupts handling

### ISSUE THREAD

**Issue by bremenpl** [facine/easyBlack#2]
Hello,
I was wondering either you are planning on adding external interrupts handling on pins in your library? That feature would help me a lot right now and I think its a great feature in general. I would aprichiate some info :).

**Comment by facine** [comment]
I'm not sure if I want to implement interruptions, but anyway you could use this other library for that: https://github.com/jackmitch/libsoc

The only way to get interrupts in user-space are using the kernel drivers and watches a state file in the sysfs to implement the interrupt. That may work, but is slow and need a lot of resources.

**Comment by bremenpl** [comment]
Is there really no other way? That would be a real bummer for me :/. Why dont you want to implement interrupts if I may ask?

**Comment by facine** [comment]
I could get to implement it in the future, but do not think is very necessary because it is not very difficult to implement it: http://www.linux.com/learn/tutorials/765810-beaglebone-black-how-to-get-interrupts-through-linux-gpio

**Comment by bremenpl** [comment]
Yes, but those are the "fake" interrupts. Its pooling, not a real interrupt. Isnt there a way to pass an interrupt event to user application?

**Comment by facine** [comment]
As far as I know, the only way to get a direct interruption is via kernel module.

**Comment by bremenpl** [comment]
I see. Is there any difference in a standard user application and a kernel module?

**Comment by facine** [comment]
http://www.tldp.org/LDP/lkmpg/2.4/html/x437.html

**Comment by bremenpl** [comment]
Thank you for help :).

W dniu 2014-11-24 o 20:13, facine pisze:

> http://www.tldp.org/LDP/lkmpg/2.4/html/x437.html
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/facine/easyBlack/issues/2#issuecomment-64246655.

## 

Bremenpl
